#!/bin/bash
swapon /dev/sdb2
mount /dev/sdb2 /mnt/gentoo/boot
mount /dev/sdb1 /mnt/gentoo
cd /mnt/gentoo

mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
