#!/bin/bash
emerge --ask  x11-terms/sakura net-wireless/blueman  x11-misc/compton app-admin/conky app-portage/layman x11-misc/polybar x11-base/xorg-drivers x11-base/xorg-server media-video/simplescreenrecorder xfce-extra/tumbler media-video/vlc x11-wm/i3-gaps www-client/google-chrome  net-im/telegram-desktop media-sound/pavucontrol app-editors/gedit net-misc/connman-gtk app-portage/eix app-portage/portage-utils app-shells/zsh app-shells/gentoo-zsh-completions x11-apps/setxkbmap media-gfx/ristretto lxde-base/lxappearance
#sys-libs/gpm

########     layman           ####
# * jorgicio                  [Git       ] (https://github.com/#jorgicio/jorgicio-gentoo.git )
# * pentoo                    [Git       ] (https://github.com/#pentoo/pentoo-overlay.git  )
# * ROKO__                    [Git       ] (https://github.com/sandikata/ROKO__.git       
emerge --ask --verbose --update --deep --newuse @world
# app-shells/zsh-autosuggestions app-shells/zsh-syntax-highlighting

USE="X bluetooth -gpm alsa unicode ABI_X86=64 dbus amd64 abi_x86_32 qt4 qt5 -gnome -kde -dvd -cdr pulseaudio i3wm"

VIDEO_CARDS="intel"
